Models/Hall.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Http;
using System.Web.Mvc;

namespace MovieProject.Models
{
    public class Hall: Entity
    {
        public Hall() {
            Seats = new List<Seat>();
        }
        public List<Seat> Seats { get; set; }
    }
}

Models/ViewModels/HallViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MovieProject.Models.ViewModels
{
    public class HallViewModel
    {
        public List<Hall> Halls { get; set; }
        public List<Hall> HallsSingle { get; set; }
        public int? HallId { get; set; }
    }
}

Controllers/HallsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieProject.Filters;
using MovieProject.Models;
using MovieProject.Models.ViewModels;
using MovieProject.Security;

namespace MovieProject.Controllers
{
    public class HallsController : Controller
    {
        private CinemaDbContext db = new CinemaDbContext();

        // GET: Halls
        [Auth]
        [Route("Hall", Name = "Index")]
        public ActionResult Index(int? id)
        {
            
            HallViewModel viewModel = null;
            try
            {
                if (id == null)
                {
                    viewModel = new HallViewModel
                    {
                        Halls = db.Halls.ToList(),
                        HallsSingle = new List<Hall>(){ },
                        HallId = 0
                    };
                }
                else
                {
                    var hall = db.Halls.Where(x => x.Id == id).FirstOrDefault();
                    viewModel = new HallViewModel
                    {
                        Halls = db.Halls.ToList(),
                        HallsSingle = new List<Hall>() { hall },
                        HallId = id
                    };
                }
                

            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
            }
            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name")] Hall hall)
        {
            Session["HallUnique"] = true;
            if (NameIsUnique(hall.Name.ToLower()))
            {
                Session["HallUnique"] = null;
                if (ModelState.IsValid)
                {
                    hall.Name = hall.Name.ToLower();
                    db.Halls.Add(hall);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public bool NameIsUnique(string name)
        {
            foreach (var item in db.Halls)
            {
                if (item.Name.ToLower() == name)
                {
                    return false;
                }
            }
            return true;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update([Bind(Include = "Id,Name")] Hall hall)
        {
            Session["HallUnique"] = true;
            if (NameIsUnique(hall.Name.ToLower()))
            {
                Session["HallUnique"] = null;
                if (ModelState.IsValid)
                {
                    hall.Name = hall.Name.ToLower();
                    db.Halls.AddOrUpdate(hall);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }

        [Auth]
        [Route("Home/Halls/{id:int}/Delete", Name = "DeleteHall")]
        public ActionResult Delete(int id)
        {
            var item = db.Halls.Where(x => x.Id == id).FirstOrDefault();
            db.Halls.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Halls/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="display:flex; justify-content: space-evenly;padding: 10px;">
    <form action=@(Model.HallId == 0 ? Url.Action("Create", "Halls") : Url.Action("Update", "Halls")) method="post" style="width: fit-content;">
        @Html.AntiForgeryToken()
        @if (Model.HallId != 0)
        {
            <input type="hidden" name="Id" value="@Model.HallId" />
        }
    <div class="form-group">
        <label>Name </label>
        <input type="text" class="form-control" name="Name" value=@(Model.HallId == 0 ? null : @Model.HallsSingle[0].Name) />
        @if (Session["HallUnique"] != null)
        {
            <div class="alert alert-danger" role="alert">
                Hall already exists
            </div>

        }
        @{Session["HallUnique"] = null; }
        
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @if (Model.HallId == 0) { 
                <input type = "submit" value = "Create" class="btn btn-default" />}
                else
                {
            <input type="submit" value="Update" class="btn btn-default" />  
                }

            </div>
        </div>
</form>
    <table class="table" style="width:unset;">
        <tr>
            <th>
                Name
            </th>
            <th>
                Action
            </th>
        </tr>

        @foreach (var item in Model.Halls)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td style="display: flex; justify-content: space-around;">
                    <a href="@Url.RouteUrl("Index", new { id=@item.Id})"><i class="far fa-edit"></i></a>
                    <a href="@Url.RouteUrl("DeleteHall", new { id=@item.Id})"><i class="fas fa-trash-alt"></i></a>
                </td>
                </tr>
                }

                </table>
            </div>